### PR TITLE
Fix EAP build

### LINKED ISSUE #105: Plugin is not compatible with latest EAP
IDE disables it on start.

PhpStorm 2018.1 EAP
Build #PS-181.3494.16, built on February 7, 2018
PhpStorm EAP User
Expiration date: March 9, 2018
JRE: 1.8.0_152-release-1136-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

### PR DESCRIPTION
**Pull request by vkhramtsov**
Fixes #105

### CODE REVIEW

**Comment by vkhramtsov** [comment]
@Haehnchen Would you be so kind to review this PR and check result? Thank you

File: travis.sh [hunk 1]
```diff
@@ -91,15 +91,17 @@ elif [ "$PHPSTORM_ENV" == "2017.2.4" ]; then
...
 
     #twig
-    download "https://plugins.jetbrains.com/files/7303/28516/twig-163.4830.18.zip"
-    unzip -qo $travisCache/twig-163.4830.18.zip -d ./plugins
+    download "https://plugins.jetbrains.com/files/7303/43344/twig-181.3741.23.zip"
+    unzip -qo $travisCache/twig-181.3741.23.zip -d ./plugins
 
     # TODO: extract latest builds for plugins from eap site they are not public
-    # https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Early+Access+Program
+    # You can extract them from pages:
```
Comment (Haehnchen) [inline travis.sh]: 👍
