### PR TITLE
Fix unable to generate Doctrine repository

### LINKED ISSUE #137: Error on add doctrine repository
Not sure what's causing this.

**The problem:**
When on an entity class name, `Alt`+`Enter` > `Add Doctrine Repository` doesn't work.

**Expected:**
A repository class is added.

**Actual:**
PHPStorm reports an error occured.

**Stacktrace:**
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'inputStream' of com/intellij/openapi/util/io/StreamUtil.readText must not be null
	at com.intellij.openapi.util.io.StreamUtil.$$$reportNull$$$0(StreamUtil.java)
	at com.intellij.openapi.util.io.StreamUtil.readText(StreamUtil.java)
	at de.espend.idea.php.annotation.doctrine.inspection.CreateEntityRepositoryIntentionAction.createEntityRepositoryContent(CreateEntityRepositoryIntentionAction.java:68)
	at de.espend.idea.php.annotation.doctrine.intention.DoctrineOrmRepositoryIntention.invoke(DoctrineOrmRepositoryIntention.java:73)
	at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.invoke(PsiElementBaseIntentionAction.java:43)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.invoke(IntentionActionWrapper.java:67)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:179)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$4(ShowIntentionActionsHandler.java:206)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:106)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:208)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$null$2(ShowIntentionActionsHandler.java:183)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$3(ShowIntentionActionsHandler.java:182)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:181)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.lambda$applyAction$0(IntentionListStep.java:103)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$12(AbstractPopup.java:1400)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:3158)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:172)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:124)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:179)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:58)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1396)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:160)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:308)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:182)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:151)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:263)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:444)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:397)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:338)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:251)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:378)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:358)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:114)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:150)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:86)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:619)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**System Details:**
```
PhpStorm 2018.3
Build #PS-183.4284.150, built on November 21, 2018
JRE: 1.8.0_152-release-1343-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3
```

**Plugin Version:**
5.3.3

### PR DESCRIPTION
**Pull request by jackbentley**
This will fix #137

Additionally updates it to select the correct directory if you store your repositories in a different namespace

### CODE REVIEW

File: src/main/java/de/espend/idea/php/annotation/doctrine/intention/DoctrineOrmRepositoryIntention.java [hunk 1]
```diff
@@ -171,15 +205,32 @@ private void insertAttribute(@NotNull Editor editor, @NotNull PhpClass phpClass,
...
+        if (descriptor.getPsiElement().getContainingFile() == null) return;
+
+        invoke(project, null, descriptor.getPsiElement().getContainingFile());
+    }
+
     @NotNull
     @Override
     public String getText() {
-        return "Add Doctrine Repository";
+        return "Add doctrine repository";
```
Comment (Haehnchen) [inline src/main/java/de/espend/idea/php/annotation/doctrine/intention/DoctrineOrmRepositoryIntention.java]: Tests are failing because of this rename

File: src/main/java/de/espend/idea/php/annotation/doctrine/intention/DoctrineOrmRepositoryIntention.java [hunk 2]
```diff
@@ -62,42 +66,68 @@ public void invoke(@NotNull Project project, Editor editor, @NotNull PsiElement
...
+            repoClass = namespace + "\\" + phpClass.getName() + "Repository";
+            repoClass = PhpLangUtil.toPresentableFQN(repoClass);
+
+            repoPhpClass = PhpElementsUtil.getClass(project, repoClass);
+        }
+
         if(repoPhpClass == null) {
-            Map<String, String> templateVars = new HashMap<>();
+            if(repositoryDir.findFile(fileName) == null) {
+                final FileTemplate fileTemplate = FileTemplateManager.getInstance(project).getTemplate("Doctrine Entity Repository");
```
Comment (Haehnchen) [inline src/main/java/de/espend/idea/php/annotation/doctrine/intention/DoctrineOrmRepositoryIntention.java]: nice idea :+1:

File: src/main/java/de/espend/idea/php/annotation/doctrine/intention/DoctrineOrmRepositoryIntention.java (hunk 1 above)
Comment (jackbentley) [reply src/main/java/de/espend/idea/php/annotation/doctrine/intention/DoctrineOrmRepositoryIntention.java]: Fixed 👍 😄

File: src/main/java/de/espend/idea/php/annotation/doctrine/intention/DoctrineOrmRepositoryIntention.java (hunk 2 above)
Comment (jackbentley) [reply src/main/java/de/espend/idea/php/annotation/doctrine/intention/DoctrineOrmRepositoryIntention.java]: Thanks! :D

**Comment by Haehnchen** [comment]
:+1:
